# Generated by Django 5.2.5 on 2025-09-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userrole_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profil',
            field=models.ImageField(upload_to='users/images/'),
        ),
    ]
