# Generated by Django 5.2.4 on 2025-08-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_alter_customer_created_by_alter_customer_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='reference',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='Référence'),
        ),
    ]
