# Generated by Django 5.2.5 on 2025-08-31 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_alter_sale_reference'),
    ]

    operations = [
    ]
