# Generated by Django 5.2.5 on 2025-08-31 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_update_sale_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='unit_price',
        ),
    ]
