# Generated by Django 5.2.5 on 2025-09-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_remove_saleitem_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='reference',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='Référence'),
        ),
    ]
