# Generated by Django 5.2.5 on 2025-09-02 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0008_alter_entry_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryitem',
            name='unit_price',
        ),
    ]
